### PR TITLE
Sort the `.gitignore` and add `.idea/jarRepositories.xml`

### PR DESCRIPTION
**Pull request by rickie**

### CODE REVIEW

**Review by Stephan202 — COMMENTED** [review]
I'm fine with this proposal :)

(Maybe we should also suggest sorting the file's entries? :thinking:.)

**Comment by rickie** [comment]
Yeah I agree, I pushed something.

**Review by Stephan202 — COMMENTED** [review]
LGTM. Suggested PR/commit message:
```
Sort `.gitignore` and add `.idea/jarRepositories.xml` to it
```

**Comment by rickie** [comment]
Opened PR upstream https://github.com/google/error-prone/pull/2616

**Pull request closed without merging**
